services:
    nextjs:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: diji-client
        ports:
            - '3000:3000'
        networks:
            - app-network
        volumes:
            - .:/app
            - /app/node_modules
        restart: always
        command: sh -c "npm run dev"

networks:
    app-network:
        driver: bridge
