version: "3.8"

services:
    nextjs:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: diji-client
        ports:
            - "3000:3000"
        networks:
            - app-network
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            NODE_ENV: development
        command: npm run dev
        restart: always

networks:
    app-network:
        driver: bridge
