// This file is generated by npm run build:icons
 
export type IconName =
	| "add"
	| "app"
	| "billing"
	| "contact"
	| "delete"
	| "edit"
	| "ia"
	| "logout"
	| "search"
	| "settings"
	| "sort"
	| "tooth"
	| "trash"
	| "upload";
