// This file is generated by npm run build:icons
 
export type IconName =
	| "app"
	| "arrow"
	| "billing"
	| "contact"
	| "dots-vertical"
	| "edit"
	| "logout"
	| "search"
	| "settings"
	| "sort"
	| "upload";
